// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dartflutt
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMQHkHBCZcbibg8pN8tyQVP0P7YTeG2w',
    appId: '1:409749988757:web:1759e809f759fee945029c',
    messagingSenderId: '409749988757',
    projectId: 'crud-test-78169',
    authDomain: 'crud-test-78169.firebaseapp.com',
    storageBucket: 'crud-test-78169.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7YmpZ4ltBSNXZjEeilLvB5dre_kE4z7g',
    appId: '1:409749988757:ios:519056e75e1aaeed45029c',
    messagingSenderId: '409749988757',
    projectId: 'crud-test-78169',
    storageBucket: 'crud-test-78169.appspot.com',
    iosBundleId: 'com.example.crudTest',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkj0OP_jPzZu3_4jFxLc2DMP94wMwnnWQ',
    appId: '1:409749988757:android:35291b273b34bdb045029c',
    messagingSenderId: '409749988757',
    projectId: 'crud-test-78169',
    storageBucket: 'crud-test-78169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YmpZ4ltBSNXZjEeilLvB5dre_kE4z7g',
    appId: '1:409749988757:ios:519056e75e1aaeed45029c',
    messagingSenderId: '409749988757',
    projectId: 'crud-test-78169',
    storageBucket: 'crud-test-78169.appspot.com',
    iosBundleId: 'com.example.crudTest',
  );

}